### ISSUE TITLE
Błąd logowania do poczty studenckiej

### ISSUE THREAD

**Issue by twojnarowski** [knnativeflow/zdalnie-na-pwr#23]
Pobrałem aplikację i zaintalowałem. Przy pierwszym uruchomieniu Krok 1 (pobranie danych do jsosa) zadziałał, ale na Kroku 2 (logowanie d
o poczty studenckiej), po wpisaniu danych i kliknięciu "Zaloguj" wyskakuje czerwony komentarz "Invalid data in ical". 
Załączam screen, usunąłem swoje wpisane dane, ale podczas klikania "Zaloguj" poprawne dane były wpisane.
![image](https://user-images.githubusercontent.com/13180578/99882762-359ea900-2c23-11eb-8e7f-5473b00b593b.png)

**Comment by waszkowski** [comment]
Dzisiaj wieczorem poleci release 1.0.2 z poprawką.
